// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:smart_expense_tracker/features/bills/data/models/bill_model.dart';
import 'package:smart_expense_tracker/features/budget/data/models/budget_model.dart';
import 'package:smart_expense_tracker/features/categories/data/models/category_model.dart';
import 'package:smart_expense_tracker/features/expenses/data/models/expense_model.dart';
import 'package:smart_expense_tracker/features/notifications/data/models/notification_model.dart';
import 'package:smart_expense_tracker/features/savings/data/models/savings_goal_model.dart';
import 'package:smart_expense_tracker/features/wallets/data/models/wallet_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(BillModelAdapter());
    registerAdapter(BudgetModelAdapter());
    registerAdapter(CategoryModelAdapter());
    registerAdapter(ExpenseModelAdapter());
    registerAdapter(NotificationModelAdapter());
    registerAdapter(SavingsGoalModelAdapter());
    registerAdapter(WalletModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(BillModelAdapter());
    registerAdapter(BudgetModelAdapter());
    registerAdapter(CategoryModelAdapter());
    registerAdapter(ExpenseModelAdapter());
    registerAdapter(NotificationModelAdapter());
    registerAdapter(SavingsGoalModelAdapter());
    registerAdapter(WalletModelAdapter());
  }
}
