import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../features/settings/presentation/providers/settings_provider.dart';

class AppLang {
  AppLang._();

  static const Map<String, Map<String, String>> translations = {
    'en': {
      'appName': 'Smart Expense Tracker',
      'navDashboard': 'Home',
      'navExpenses': 'Transaction',
      'navAnalytics': 'Analytics',
      'navSettings': 'Account',
      'navProfile': 'Profile',
      
      // Dashboard
      'thisMonthSpend': 'This Month Spend',
      'spendingWallet': 'Spending Wallet',
      'recentTransactions': 'Recent Transactions',
      'seeAll': 'See All',
      'belowLastMonth': 'below last month',
      'aboveLastMonth': 'above last month',
      'noExpenses': 'No expenses yet',
      'noExpensesDesc': 'Tap + to add your first expense',
      
      // Settings / Profile
      'settings': 'Settings',
      'profile': 'My Profile',
      'editProfile': 'Edit Profile',
      'appearance': 'Appearance',
      'darkMode': 'Dark Mode',
      'language': 'Language',
      'english': 'English',
      'arabic': 'Arabic',
      'security': 'Security',
      'changePIN': 'Change PIN',
      'enableBiometric': 'Enable biometric unlock',
      'lockPolicy': 'PIN Lock Policy',
      'lockOnLaunch': 'Only on app launch',
      'lockAfter5': 'After 5 minutes idle',
      'lockAfter10': 'After 10 minutes idle',
      'lockAfter15': 'After 15 minutes idle',
      'neverLock': 'Never (until sign out)',
      'manageBudgets': 'Manage Budgets',
      'manageCategories': 'Manage Categories',
      'export': 'Export',
      'exportReport': 'Export Report',
      'pdfOrCsv': 'PDF or CSV',
      'about': 'About',
      'version': 'Version 1.0.0',
      'memberSince': 'Member Since',
      'totalBalance': 'Total Balance',
      'wallets': 'Wallets',
      'transactionCount': 'Transactions',
      'spentThisMonth': 'Spent This Month',
      'spentToday': 'Spent Today',
      'lockApp': 'Lock App',
      'fullName': 'Full Name',
      'password': 'Password',
      'changePassword': 'Change Password',
      'removePhoto': 'Remove Photo',
      'changePhoto': 'Change Photo',
      
      // Common actions
      'save': 'Save',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'edit': 'Edit',
      'confirm': 'Confirm',
      'retry': 'Retry',
      'loading': 'Loading…',
      'signOut': 'Sign Out',

      // Authentication & Onboarding
      'email': 'Email',
      'enterEmail': 'Enter email',
      'emailRequired': 'Please enter your email',
      'enterPassword': 'Enter password',
      'passwordRequired': 'Please enter your password',
      'passwordLength': 'Password must be at least 6 characters',
      'confirmPassword': 'Confirm Password',
      'confirmPasswordHint': 'Re-enter password',
      'confirmPasswordRequired': 'Please confirm your password',
      'passwordsDoNotMatch': 'Passwords do not match',
      'login': 'Log In',
      'signup': 'Sign Up',
      'dontHaveAccount': "Don't have an account? ",
      'alreadyHaveAccount': 'Already have an account? ',
      'rememberMe': 'Remember me',
      'welcomeBack': 'Welcome Back',
      'getStartedWithCashio': 'Get Started with Cashio',
      'createSecureWallet': 'Create your secure wallet in just a few steps.',
      'accessSecureWallet': 'Access your secure wallet in just a few steps.',
      'enterFullName': 'Enter your full name',
      'fullNameRequired': 'Please enter your full name',
      'authError': 'Authentication Error',
      'ok': 'OK',
      'or': 'Or',
      'apple': 'Apple',
      'google': 'Google',
      'termsConditionPrefixSignUp': 'By creating an account, you agree to our ',
      'termsConditionPrefixLogIn': 'By logging in, you agree to our ',
      'terms': 'Terms & Conditions',
      'and': ' and ',
      'privacyPolicy': 'Privacy Policy',
      'chooseFromGallery': 'Choose from Gallery',
      'newPinLabel': 'New 4-digit PIN',
      'newPasswordLabel': 'New Password',
      'passwordUpdatedSuccess': 'Password updated successfully',
      'errorPrefix': 'Error',
      'update': 'Update',
      'noWalletsYet': 'No wallets yet',
      'createPinDesc': 'Create a 4-digit PIN to protect your data',
      'confirmPinDesc': 'Re-enter your 4-digit PIN',
      'enterPin': 'Enter PIN',
      'confirmPin': 'Confirm PIN',
      'setupPin': 'Set Up PIN',
      'pinMismatch': 'PINs do not match. Try again.',
      'pinIncorrect': 'Incorrect PIN',
      'biometric': 'Use Biometrics',

      // Error states
      'somethingWrong': 'Something went wrong',
      'tryAgain': 'Please try again',

      // Budget screen
      'budget': 'Budget',
      'noBudget': 'No budgets set',
      'noBudgetDesc': 'Set a budget to track your spending',
      'setBudget': 'Set Budget',
      'monthlyBudget': 'Monthly Budget',
      'budgetAmount': 'Budget Amount',
      'budgetAlertOver': '⚠️ You have exceeded your budget!',
      'budgetAlert80': '⚠️ You have used 80% of your budget.',
      'setMonthlyBudget': 'Set Monthly Budget',
      'categoryBudgets': 'Category Budgets',
      'addBudget': 'Add',
      'noCategoryBudgets': 'No category budgets set.',
      'overall': 'Overall',
      'category': 'Category',
      'used': 'used',
      'remaining': 'remaining',

      // Categories screen
      'categories': 'Categories',
      'noCategories': 'No categories yet',
      'addCategory': 'Add Category',
      'editCategory': 'Edit Category',
      'deleteCategory': 'Delete Category',
      'deleteCategoryConfirm': 'Expenses using this category won\'t be deleted.',
      'categoryName': 'Category Name',
      'pickIcon': 'Pick Icon',
      'pickColor': 'Pick Color',

      // Expenses
      'addExpense': 'Add Expense',
      'editExpense': 'Edit Expense',
      'deleteExpense': 'Delete Expense',
      'expenseTitle': 'Title',
      'expenseNote': 'Note',
      'searchExpenses': 'Search expenses…',
      'allCategories': 'All Categories',
      'sortBy': 'Sort by',
      'expenseNotFound': 'Expense not found',
      'selectCategory': 'Please select a category',
      'noWalletsFound': 'No wallets found',
      'errorLoadingCategories': 'Error loading categories',
      'recurringTransaction': 'Recurring Transaction',
      'attachReceipt': 'Attach Receipt',
      'transactionType': 'Transaction Type',
      'paymentWallet': 'Payment Wallet',
      'allWallets': 'All Wallets',
      'errorLoadingWallets': 'Error loading wallets',
      'amountRange': 'Amount Range',
      'hasReceipt': 'Has Receipt Attachment',
      'clearAll': 'Clear All',
      'apply': 'Apply',

      // Sort options
      'newestFirst': 'Newest first',
      'oldestFirst': 'Oldest first',
      'highestAmount': 'Highest amount',
      'lowestAmount': 'Lowest amount',
      'byCategory': 'By category',
      'allTransactions': 'All',

      // Delete confirmation
      'deleteConfirmMsg': 'This cannot be undone.',

      // Notification strings
      'notifInactiveTitle': 'Track Your Expenses',
      'notifInactiveBody': "You haven't added any expenses in the last 3 days. Stay on top of your budget!",
      'notifBudgetExceededTitle': 'Budget Exceeded!',
      'notifBudgetExceededBody': 'You have exceeded your budget for this category.',
      'notifBudgetAlertTitle': 'Budget Alert',
      'notifBudgetAlertBody': 'You have spent over 80% of your category budget.',
      'notifBillTitle': 'Upcoming Bill',
      'notifBillDue': 'Your bill is due in',
      'notifDaysLeft': 'days left',
      'notifGoalTitle': 'Goal Achieved! 🏆',
      'notifGoalCompletedBody': 'Congratulations! You reached your savings target.',

      // Wallets
      'myWallets': 'My Wallets',
      'selectWalletColor': 'Select Wallet Color',
      'selectWalletIcon': 'Select Wallet Icon',
      'transferFunds': 'Transfer Funds',
      'transferMoney': 'Transfer Money',
      'goBack': 'Go Back',

      // Category labels
      'custom': 'Custom',
      'defaultLabel': 'Default',

      // Wallet form
      'addWallet': 'Add Wallet',
      'editWallet': 'Edit Wallet',
      'walletName': 'Wallet Name',
      'initialBalance': 'Initial Balance',
      'walletType': 'Wallet Type',
      'currency': 'Currency',
      'required': 'Required',
      'invalidBalance': 'Invalid balance',
      'saveChanges': 'Save Changes',
      'createWallet': 'Create Wallet',
      'preview': 'Preview',

      // Transfer screen
      'multipleWalletsRequired': 'Multiple Wallets Required',
      'multipleWalletsDesc': 'You need at least two wallets to perform a transfer.',
      'fromWallet': 'From Wallet',
      'toWallet': 'To Wallet',
      'transferAmount': 'Transfer Amount',
      'transferDate': 'Transfer Date',
      'notesReason': 'Notes / Reason',
      'executeTransfer': 'Execute Transfer',
      'invalidAmount': 'Invalid amount',
      'signOutConfirm': 'Are you sure you want to sign out?',
      'notifications': 'Notifications',
      'markAllRead': 'Mark all read',
      'allCaughtUp': 'All Caught Up!',
      'noNotifications': 'No new notifications to show right now.',
      'today': 'Today',
      'yesterday': 'Yesterday',
      'earlier': 'Earlier',
      'topCategory': 'Top Category',
      'exportPdf': 'Export as PDF',
      'exportCsv': 'Export as CSV',
      'generating': 'Generating…',
      'exportTitle': 'Export your expense report',
      'exportSubtitle': 'All expenses are included in the report.',
      'pdfDesc': 'A formatted PDF report with table and totals',
      'csvDesc': 'Raw data in CSV format for spreadsheets',
      'exportFailed': 'Export failed',
      'income': 'Income',
      'expense': 'Expense',
      'transfer': 'Transfer',
      'cash': 'Cash',
      'bank': 'Bank Account',
      'visa': 'Visa',
      'mastercard': 'Mastercard',
      'vodafoneCash': 'Vodafone Cash',
      'instapay': 'InstaPay',
      'other': 'Other',
      'none': 'None',
      'daily': 'Daily',
      'all': 'All',
      'advancedFilters': 'Advanced Filters',
      'minAmount': 'Min Amount',
      'maxAmount': 'Max Amount',
      'selectWallet': 'Select Wallet',
      'merchant': 'Merchant',
      'tags': 'Tags',
      'addTag': 'Add Tag',
      'date': 'Date',
      'receiptImage': 'Receipt Image',
      'addNotes': 'Add notes',
      'updateTransaction': 'Update Transaction',
      'saveTransaction': 'Save Transaction',

      // RecurringInterval
      'weekly': 'Weekly',
      'monthly': 'Monthly',
      'yearly': 'Yearly',

      // Bills screen
      'addBillSub': 'Add Bill / Subscription',
      'editBillSub': 'Edit Bill / Subscription',
      'billName': 'Bill Name / Service',
      'amountDue': 'Amount Due',
      'walletSource': 'Wallet Source',
      'dueDate': 'Due Date',
      'isRecurringSubscription': 'Is Recurring Subscription?',
      'subscriptionExample': 'E.g. Netflix, Spotify, gym membership',
      'billingCycle': 'Billing Cycle',
      'reminderDaysBefore': 'Reminder days before',
      'notesDesc': 'Notes / Description',
      'createBill': 'Create Bill',

      // Transaction / Expense Detail
      'expenseDetail': 'Transaction Detail',
      'deleteConfirmTitle': 'Delete Transaction',

      // Analytics
      'noExpensesThisMonth': 'No expenses this month',
      'balance': 'Balance',
      'spent': 'spent',
      'of': 'of',
      'categoryBreakdown': 'Category Breakdown',
      'overview': 'Overview',
      'noData': 'No data',
      'moreLastMonth': 'more than last month',
      'lessLastMonth': 'less than last month',

      // Date range display
      'dateUntil': 'Until',
      'dateFrom': 'From',

      // Dashboard Quick Access
      'quickAccess': 'Quick Access',
      'manageLimit': 'Manage limits',
      'trackGoals': 'Track goals',
      'upcomingBills': 'Upcoming bills',
      'recurringPayments': 'Recurring payments',
      'savings': 'Savings',
      'bills': 'Bills',

      // Notifications (dynamic localization)
      'notifBillAmount': 'Amount',
      'mainWallet': 'Main Wallet',
      'onboardSkip': 'Skip',
      'onboardNext': 'Next',
      'onboardGetStarted': 'Get Started',

      'onboardTitle1': 'Track Your Spending',
      'onboardDesc1':
      'Control your spending immediately with automatic bank connection and clean category charts.',

      'onboardTitle2': 'Your Finances in One Place',
      'onboardDesc2':
      'Get the big picture on all your money. Connect your bank, track cash, or import data.',

      'onboardTitle3': 'Invite Other People',
      'onboardDesc3':
      'Connect all your accounts from any bank. Add savings, credit cards, PayPal and more.',

      'onboardExpenseLabel': 'Expense Total in July',
      'onboardSpendingLabel': 'Spending',
      'onboardBillsUtilities': 'Bills & Utilities',

      'onboardEarnRewardsTitle': 'Earn Rewards',
      'onboardEarnRewardsSubtitle': 'Invite & earn bonus when friends join.',

      'onboardEasySharingTitle': 'Easy Sharing',
      'onboardEasySharingSubtitle': 'Share your link in just one tap.',

      'onboardTrackReferralsTitle': 'Track Referrals',
      'onboardTrackReferralsSubtitle': 'See who joined and what you earn.',
    },
    'ar': {
      'appName': 'مراقب النفقات الذكي',
      'navDashboard': 'الرئيسية',
      'navExpenses': 'المعاملات',
      'navAnalytics': 'التحليلات',
      'navSettings': 'الحساب',
      'navProfile': 'الملف الشخصي',
      
      // Dashboard
      'thisMonthSpend': 'إنفاق هذا الشهر',
      'spendingWallet': 'محفظة الإنفاق',
      'recentTransactions': 'المعاملات الأخيرة',
      'seeAll': 'عرض الكل',
      'belowLastMonth': 'أقل من الشهر الماضي',
      'aboveLastMonth': 'أعلى من الشهر الماضي',
      'noExpenses': 'لا توجد نفقات بعد',
      'noExpensesDesc': 'انقر على + لإضافة نفقتك الأولى',
      
      // Settings / Profile
      'settings': 'الإعدادات',
      'profile': 'ملفي الشخصي',
      'editProfile': 'تعديل الملف',
      'appearance': 'المظهر',
      'darkMode': 'الوضع الداكن',
      'language': 'اللغة',
      'english': 'الإنجليزية',
      'arabic': 'العربية',
      'security': 'الأمان',
      'changePIN': 'تغيير رمز PIN',
      'enableBiometric': 'تمكين فتح القفل بالبصمة',
      'lockPolicy': 'سياسة قفل PIN',
      'lockOnLaunch': 'عند تشغيل التطبيق فقط',
      'lockAfter5': 'بعد 5 دقائق خمول',
      'lockAfter10': 'بعد 10 دقائق خمول',
      'lockAfter15': 'بعد 15 دقيقة خمول',
      'neverLock': 'أبداً (حتى تسجيل الخروج)',
      'manageBudgets': 'إدارة الميزانيات',
      'manageCategories': 'إدارة الفئات',
      'export': 'تصدير',
      'exportReport': 'تصدير التقارير',
      'pdfOrCsv': 'PDF أو CSV',
      'about': 'حول التطبيق',
      'version': 'الإصدار 1.0.0',
      'memberSince': 'عضو منذ',
      'totalBalance': 'الرصيد الإجمالي',
      'wallets': 'المحافظ',
      'transactionCount': 'المعاملات',
      'spentThisMonth': 'إنفاق هذا الشهر',
      'spentToday': 'إنفاق اليوم',
      'lockApp': 'قفل التطبيق',
      'fullName': 'الاسم الكامل',
      'password': 'كلمة المرور',
      'changePassword': 'تغيير كلمة المرور',
      'removePhoto': 'إزالة الصورة',
      'changePhoto': 'تغيير الصورة',
      
      // Common actions
      'save': 'حفظ',
      'cancel': 'إلغاء',
      'delete': 'حذف',
      'edit': 'تعديل',
      'confirm': 'تأكيد',
      'retry': 'إعادة المحاولة',
      'loading': 'جاري التحميل…',
      'signOut': 'تسجيل الخروج',

      // Authentication & Onboarding
      'email': 'البريد الإلكتروني',
      'enterEmail': 'أدخل البريد الإلكتروني',
      'emailRequired': 'الرجاء إدخال البريد الإلكتروني',
      'enterPassword': 'أدخل كلمة المرور',
      'passwordRequired': 'الرجاء إدخال كلمة المرور',
      'passwordLength': 'يجب أن تتكون كلمة المرور من 6 أحرف على الأقل',
      'confirmPassword': 'تأكيد كلمة المرور',
      'confirmPasswordHint': 'أعد إدخال كلمة المرور',
      'confirmPasswordRequired': 'الرجاء تأكيد كلمة المرور',
      'passwordsDoNotMatch': 'كلمتا المرور غير متطابقتين',
      'login': 'تسجيل الدخول',
      'signup': 'إنشاء حساب',
      'dontHaveAccount': 'ليس لديك حساب؟ ',
      'alreadyHaveAccount': 'لديك حساب بالفعل؟ ',
      'rememberMe': 'تذكرني',
      'welcomeBack': 'مرحباً بعودتك',
      'getStartedWithCashio': 'ابدأ مع كاشيو',
      'createSecureWallet': 'أنشئ محفظتك الآمنة في خطوات بسيطة.',
      'accessSecureWallet': 'الوصول إلى محفظتك الآمنة في خطوات بسيطة.',
      'enterFullName': 'أدخل اسمك الكامل',
      'fullNameRequired': 'الرجاء إدخال اسمك الكامل',
      'authError': 'خطأ في المصادقة',
      'ok': 'موافق',
      'or': 'أو',
      'apple': 'أبل',
      'google': 'جوجل',
      'termsConditionPrefixSignUp': 'بإنشاء حساب، فإنك توافق على ',
      'termsConditionPrefixLogIn': 'بتسجيل الدخول، فإنك توافق على ',
      'terms': 'الشروط والأحكام',
      'and': ' و ',
      'privacyPolicy': 'سياسة الخصوصية',
      'chooseFromGallery': 'اختر من المعرض',
      'newPinLabel': 'رمز PIN جديد من 4 أرقام',
      'newPasswordLabel': 'كلمة المرور الجديدة',
      'passwordUpdatedSuccess': 'تم تحديث كلمة المرور بنجاح',
      'errorPrefix': 'خطأ',
      'update': 'تحديث',
      'noWalletsYet': 'لا توجد محافظ بعد',
      'createPinDesc': 'قم بإنشاء رمز PIN مكون من 4 أرقام لحماية بياناتك',
      'confirmPinDesc': 'أعد إدخال رمز PIN المكون من 4 أرقام',
      'enterPin': 'أدخل رمز PIN',
      'confirmPin': 'تأكيد رمز PIN',
      'setupPin': 'إعداد رمز PIN',
      'pinMismatch': 'رموز PIN غير متطابقة. حاول مرة أخرى.',
      'pinIncorrect': 'رمز PIN غير صحيح',
      'biometric': 'استخدام البصمة',

      // Error states
      'somethingWrong': 'حدث خطأ ما',
      'tryAgain': 'الرجاء المحاولة مرة أخرى',

      // Budget screen
      'budget': 'الميزانية',
      'noBudget': 'لا توجد ميزانيات',
      'noBudgetDesc': 'حدد ميزانية لتتبع إنفاقك',
      'setBudget': 'تحديد الميزانية',
      'monthlyBudget': 'الميزانية الشهرية',
      'budgetAmount': 'مبلغ الميزانية',
      'budgetAlertOver': '⚠️ لقد تجاوزت ميزانيتك!',
      'budgetAlert80': '⚠️ لقد استخدمت 80٪ من ميزانيتك.',
      'setMonthlyBudget': 'تعيين الميزانية الشهرية',
      'categoryBudgets': 'ميزانيات الفئات',
      'addBudget': 'إضافة',
      'noCategoryBudgets': 'لا توجد ميزانيات للفئات.',
      'overall': 'إجمالي',
      'category': 'الفئة',
      'used': 'مستخدم',
      'remaining': 'متبقي',

      // Categories screen
      'categories': 'الفئات',
      'noCategories': 'لا توجد فئات بعد',
      'addCategory': 'إضافة فئة',
      'editCategory': 'تعديل الفئة',
      'deleteCategory': 'حذف الفئة',
      'deleteCategoryConfirm': 'لن يتم حذف النفقات التي تستخدم هذه الفئة.',
      'categoryName': 'اسم الفئة',
      'pickIcon': 'اختر أيقونة',
      'pickColor': 'اختر لوناً',

      // Expenses
      'addExpense': 'إضافة معاملة',
      'editExpense': 'تعديل المعاملة',
      'deleteExpense': 'حذف المعاملة',
      'expenseTitle': 'العنوان',
      'expenseNote': 'ملاحظة',
      'searchExpenses': 'البحث في المعاملات…',
      'allCategories': 'جميع الفئات',
      'sortBy': 'ترتيب حسب',
      'expenseNotFound': 'المعاملة غير موجودة',
      'selectCategory': 'الرجاء اختيار فئة',
      'noWalletsFound': 'لا توجد محافظ',
      'errorLoadingCategories': 'خطأ في تحميل الفئات',
      'recurringTransaction': 'معاملة متكررة',
      'attachReceipt': 'إرفاق إيصال',
      'transactionType': 'نوع المعاملة',
      'paymentWallet': 'محفظة الدفع',
      'allWallets': 'جميع المحافظ',
      'errorLoadingWallets': 'خطأ في تحميل المحافظ',
      'amountRange': 'نطاق المبلغ',
      'hasReceipt': 'يحتوي على إيصال',
      'clearAll': 'مسح الكل',
      'apply': 'تطبيق',

      // Wallets
      'myWallets': 'محافظي',
      'selectWalletColor': 'اختر لون المحفظة',
      'selectWalletIcon': 'اختر أيقونة المحفظة',
      'transferFunds': 'تحويل الأموال',
      'transferMoney': 'تحويل مال',
      'goBack': 'العودة',

      // Category labels
      'custom': 'مخصص',
      'defaultLabel': 'افتراضي',

      // Wallet form
      'addWallet': 'إضافة محفظة',
      'editWallet': 'تعديل المحفظة',
      'walletName': 'اسم المحفظة',
      'initialBalance': 'الرصيد الابتدائي',
      'walletType': 'نوع المحفظة',
      'currency': 'العملة',
      'required': 'مطلوب',
      'invalidBalance': 'رصيد غير صحيح',
      'saveChanges': 'حفظ التغييرات',
      'createWallet': 'إنشاء محفظة',
      'preview': 'معاينة',

      // Transfer screen
      'multipleWalletsRequired': 'مطلوب محافظ متعددة',
      'multipleWalletsDesc': 'تحتاج إلى محفظتين على الأقل لإجراء تحويل.',
      'fromWallet': 'من المحفظة',
      'toWallet': 'إلى المحفظة',
      'transferAmount': 'مبلغ التحويل',
      'transferDate': 'تاريخ التحويل',
      'notesReason': 'ملاحظات / سبب',
      'executeTransfer': 'تنفيذ التحويل',
      'invalidAmount': 'مبلغ غير صحيح',
      'signOutConfirm': 'هل أنت متأكد أنك تريد تسجيل الخروج؟',
      'notifications': 'الإشعارات',
      'markAllRead': 'تحديد الكل كمقروء',
      'allCaughtUp': 'كل شيء جاهز!',
      'noNotifications': 'لا توجد إشعارات جديدة لعرضها الآن.',
      'today': 'اليوم',
      'yesterday': 'أمس',
      'earlier': 'سابقاً',
      'topCategory': 'أعلى فئة',
      'exportPdf': 'تصدير كـ PDF',
      'exportCsv': 'تصدير كـ CSV',
      'generating': 'جاري التوليد…',
      'exportTitle': 'تصدير تقرير النفقات',
      'exportSubtitle': 'سيتم تضمين جميع النفقات في التقرير.',
      'pdfDesc': 'تقرير PDF منسق بجدول ومجاميع',
      'csvDesc': 'بيانات خام بتنسيق CSV لبرامج جداول البيانات',
      'exportFailed': 'فشل التصدير',
      'income': 'الدخل',
      'expense': 'المصروفات',
      'transfer': 'تحويل',
      'cash': 'نقد',
      'bank': 'حساب بنكي',
      'visa': 'فيزا',
      'mastercard': 'ماستركارد',
      'vodafoneCash': 'فودافون كاش',
      'instapay': 'إنستاباي',
      'other': 'أخرى',
      'none': 'لا يوجد',
      'daily': 'يومي',
      'all': 'الكل',
      'advancedFilters': 'مرشحات متقدمة',
      'minAmount': 'الحد الأدنى',
      'maxAmount': 'الحد الأقصى',
      'selectWallet': 'اختر المحفظة',
      'merchant': 'التاجر',
      'tags': 'الوسوم',
      'addTag': 'إضافة وسم',
      'date': 'التاريخ',
      'receiptImage': 'صورة الإيصال',
      'addNotes': 'إضافة ملاحظات',
      'updateTransaction': 'تحديث المعاملة',
      'saveTransaction': 'حفظ المعاملة',

      // RecurringInterval
      'weekly': 'أسبوعي',
      'monthly': 'شهري',
      'yearly': 'سنوي',

      // Bills screen
      'addBillSub': 'إضافة فاتورة / اشتراك',
      'editBillSub': 'تعديل الفاتورة / الاشتراك',
      'billName': 'اسم الفاتورة / الخدمة',
      'amountDue': 'المبلغ المستحق',
      'walletSource': 'محفظة المصدر',
      'dueDate': 'تاريخ الاستحقاق',
      'isRecurringSubscription': 'هل هو اشتراك متكرر؟',
      'subscriptionExample': 'مثل: نتفليكس، سبوتيفاي، عضوية الجيم',
      'billingCycle': 'دورة الفوترة',
      'reminderDaysBefore': 'أيام التذكير قبل الموعد',
      'notesDesc': 'ملاحظات / وصف',
      'createBill': 'إنشاء فاتورة',

      // Transaction / Expense Detail
      'expenseDetail': 'تفاصيل المعاملة',
      'deleteConfirmTitle': 'حذف المعاملة',

      // Analytics
      'noExpensesThisMonth': 'لا توجد نفقات هذا الشهر',
      'balance': 'الرصيد',
      'spent': 'مُنفق',
      'of': 'من',
      'categoryBreakdown': 'تفصيل الفئات',
      'overview': 'نظرة عامة',
      'noData': 'لا توجد بيانات',
      'moreLastMonth': 'أكثر من الشهر الماضي',
      'lessLastMonth': 'أقل من الشهر الماضي',

      // Date range display
      'dateUntil': 'حتى',
      'dateFrom': 'من',

      // Dashboard Quick Access
      'quickAccess': 'وصول سريع',
      'manageLimit': 'إدارة الحدود',
      'trackGoals': 'تتبع الأهداف',
      'upcomingBills': 'فواتير قادمة',
      'recurringPayments': 'مدفوعات متكررة',
      'savings': 'المدخرات',
      'bills': 'الفواتير',

      // Notifications (dynamic localization)
      'notifInactiveTitle': 'تتبع نفقاتك',
      'notifInactiveBody': 'لم تُضف أي نفقات في آخر 3 أيام. ابقَ على اطلاع بميزانيتك!',
      'notifBudgetExceededTitle': 'تجاوزت الميزانية!',
      'notifBudgetExceededBody': 'لقد تجاوزت ميزانيتك لهذه الفئة.',
      'notifBudgetAlertTitle': 'تنبيه الميزانية',
      'notifBudgetAlertBody': 'لقد أنفقت أكثر من 80٪ من ميزانية الفئة.',
      'notifBillTitle': 'فاتورة قادمة',
      'notifGoalTitle': 'تم تحقيق الهدف! 🏆',
      'notifGoalCompletedBody': 'تهانينا! لقد وصلت إلى هدف مدخراتك!',
      'notifBillDue': 'فاتورتك مستحقة خلال',
      'notifBillAmount': 'المبلغ',
      'notifDaysLeft': 'أيام متبقية',
      'mainWallet': 'المحفظة الرئيسية',
      'onboardSkip': 'تخطي',
      'onboardNext': 'التالي',
      'onboardGetStarted': 'ابدأ الآن',

      'onboardTitle1': 'تابع مصروفاتك',
      'onboardDesc1':
      'تحكم في مصروفاتك فورًا من خلال الربط التلقائي مع البنك ورسوم بيانية واضحة للفئات.',

      'onboardTitle2': 'كل أموالك في مكان واحد',
      'onboardDesc2':
      'احصل على نظرة شاملة على أموالك. اربط حسابك البنكي، تابع النقد، أو استورد بياناتك.',

      'onboardTitle3': 'ادعُ أشخاصًا آخرين',
      'onboardDesc3':
      'اربط جميع حساباتك من أي بنك. أضف المدخرات، بطاقات الائتمان، PayPal والمزيد.',

      'onboardExpenseLabel': 'إجمالي المصروفات في يوليو',
      'onboardSpendingLabel': 'الإنفاق',
      'onboardBillsUtilities': 'الفواتير والمرافق',

      'onboardEarnRewardsTitle': 'اكسب المكافآت',
      'onboardEarnRewardsSubtitle': 'ادعُ أصدقاءك واكسب مكافأة عند انضمامهم.',

      'onboardEasySharingTitle': 'مشاركة سهلة',
      'onboardEasySharingSubtitle': 'شارك رابطك بضغطة واحدة فقط.',

      'onboardTrackReferralsTitle': 'تتبع الإحالات',
      'onboardTrackReferralsSubtitle': 'تعرّف على من انضم وماذا كسبت.',
    }
  };
}

extension RefTrExtension on WidgetRef {
  String tr(String key) {
    try {
      final locale = watch(localeProvider);
      return AppLang.translations[locale.languageCode]?[key] ?? AppLang.translations['en']?[key] ?? key;
    } catch (_) {
      return AppLang.translations['en']?[key] ?? key;
    }
  }
}
